language: python

# Use container-based infrastructure
sudo: false

matrix:
  include:
    - env: TOX_ENV=py27-cryptography
      python: 2.7
    - env: TOX_ENV=py27-pycrypto
      python: 2.7
    - env: TOX_ENV=py34-cryptography
      python: 3.4
    - env: TOX_ENV=py34-pycrypto
      python: 3.4
    - env: TOX_ENV=py35-cryptography
      python: 3.5
    - env: TOX_ENV=py35-pycrypto
      python: 3.5
    - env: TOX_ENV=py36-cryptography
      python: 3.6
    - env: TOX_ENV=py36-pycrypto
      python: 3.6
    - env: TOX_ENV=pypy-cryptography
      python: "pypy-5.3.1"
    - env: TOX_ENV=pypy-pycrypto
      python: "pypy-5.3.1"

services:
  - redis-server
  - memcached

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox
  - pip install coverage

script: tox -e $TOX_ENV

after_success:
  - pip install scrutinizer-ocular codecov
  - ocular
  - codecov

deploy:
  provider: pypi
  on:
    tags: true
    python: 3.6
    condition: "$TOX_ENV = py36-cryptography"
  distributions: "sdist bdist_wheel"

notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/56c9af5a787e8c742f81
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
