language: python

# Use container-based infrastructure
sudo: false

matrix:
  include:
    - env: TOX_ENV=py26-cryptography
    - env: TOX_ENV=py26-pycrypto
    - env: TOX_ENV=py27-cryptography
    - env: TOX_ENV=py27-pycrypto
    - env: TOX_ENV=py33-cryptography
    - env: TOX_ENV=py33-pycrypto
    - env: TOX_ENV=py34-cryptography
    - env: TOX_ENV=py34-pycrypto
    - env: TOX_ENV=py35-cryptography
      python: 3.5
    - env: TOX_ENV=py35-pycrypto
      python: 3.5
    - env: TOX_ENV=pypy-cryptography
    - env: TOX_ENV=pypy-pycrypto

services:
  - redis-server
  - memcached

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox
  - pip install coverage

script: tox -e $TOX_ENV

after_success:
  - pip install scrutinizer-ocular codecov
  - ocular
  - codecov

notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/56c9af5a787e8c742f81
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
